<?php

namespace App\Http\Resources\Api\V3\Oem;

use App\Http\Resources\HasJsonSchema;
use App\Models\Layout;
use App\Models\Oem;
use App\Models\Scopes\ByUser;
use App\Models\Tag;
use App\Models\User;
use App\Models\Warning;
use App\Models\Warning\Scopes\ByTitles;
use App\Types\TaggableType;
use Illuminate\Http\Resources\Json\JsonResource;

/**
 * @property Oem $resource
 */
class DetailedResource extends JsonResource implements HasJsonSchema
{
    private Layout $layout;
    private User   $user;

    public function __construct(Oem $resource, Layout $layout, User $user)
    {
        parent::__construct($resource);
        $this->layout = $layout;
        $this->user   = $user;
    }

    public function toArray($request)
    {
        $oem       = $this->resource;
        $modelType = $oem->modelType;
        $tags      = TaggableType::query(Tag::TYPE_MODEL_TYPE, $oem->series->getRouteKey())->paginate(15);
        $warnings  = Warning::scoped(new ByTitles(explode(',', $oem->warnings)))->paginate();
        $favorite  = $oem->oemUsers()->scoped(new ByUser($this->user))->exists();

        return [
            'id'                      => $oem->getRouteKey(),
            'status'                  => $oem->status,
            'series'                  => new SeriesResource($oem->series),
            'model'                   => $oem->model,
            'logo'                    => $oem->logo,
            'image'                   => $oem->unit_image,
            'call_group_tags'         => $oem->call_group_tags,
            'calling_groups'          => $oem->calling_groups,
            'type'                    => $modelType ? $modelType->name : null,
            'model_description'       => $oem->model_description,
            'model_notes'             => $oem->model_notes,
            'tonnage'                 => $oem->tonnage,
            'total_circuits'          => $oem->total_circuits,
            'dx_chiller'              => $oem->dx_chiller,
            'cooling_type'            => $oem->cooling_type,
            'heating_type'            => $oem->heating_type,
            'seer'                    => $oem->seer,
            'eer'                     => $oem->eer,
            'refrigerant'             => $oem->refrigerant,
            'original_charge_oz'      => $oem->original_charge_oz,
            'compressor_brand'        => $oem->compressor_brand,
            'compressor_type'         => $oem->compressor_type,
            'compressor_model'        => $oem->compressor_model,
            'total_compressors'       => $oem->total_compressors,
            'compressors_per_circuit' => $oem->compressors_per_circuit,
            'compressor_sizes'        => $oem->compressor_sizes,
            'rla'                     => $oem->rla,
            'lra'                     => $oem->lra,
            'capacity_staging'        => $oem->capacity_staging,
            'lowest_staging'          => $oem->lowest_staging,
            'compressor_notes'        => $oem->compressor_notes,
            'oil_type'                => $oem->oil_type,
            'device_type'             => $oem->device_type,
            'devices_per_circuit'     => $oem->devices_per_circuit,
            'total_devices'           => $oem->total_devices,
            'device_size'             => $oem->device_size,
            'metering_device_notes'   => $oem->metering_device_notes,
            'fan_type'                => $oem->fan_type,
            'cfm_range'               => $oem->cfm_range,
            'fan_notes'               => $oem->fan_notes,
            'voltage_phase_hz'        => $oem->voltage_phase_hz,
            'conversion_job'          => $oem->conversion_job,
            'bid_type'                => $oem->bid_type,
            'man_hours'               => $oem->man_hours,
            'charge_lbs'              => $oem->charge_lbs,
            'exv'                     => $oem->exv,
            'exv_qty'                 => $oem->exv_qty,
            'exv_2'                   => $oem->exv_2,
            'exv_2_qty'               => $oem->exv_2_qty,
            'control_panel'           => $oem->control_panel,
            'inspect'                 => $oem->inspect,
            'baseline'                => $oem->baseline,
            'airflow_waterflow'       => $oem->airflow_waterflow,
            'recover'                 => $oem->recover,
            'controls'                => $oem->controls,
            'replace_install'         => $oem->replace_install,
            'leak_check'              => $oem->leak_check,
            'evacuate'                => $oem->evacuate,
            'charge'                  => $oem->charge,
            'tune'                    => $oem->tune,
            'verify'                  => $oem->verify,
            'label'                   => $oem->label,
            'conversion_notes'        => $oem->conversion_notes,
            'date_added'              => $oem->date_added,
            'qa'                      => $oem->qa,
            'qa_qc_comments'          => $oem->qa_qc_comments,
            'last_qc_date'            => $oem->last_qc_date,
            'info_source'             => $oem->info_source,
            'source'                  => $oem->source,
            'match'                   => $oem->match,
            'syncing_notes'           => $oem->syncing_notes,
            'layout'                  => $this->layout,
            'tags'                    => new TagCollection($tags),
            'manuals'                 => new ManualsResource($oem),
            'conversions'             => new ConversionJobsResource($oem),
            'warnings'                => new WarningCollection($warnings),
            'functional_parts_count'  => $this->resource->functionalPartsCount(),
            'posts_count'             => $this->resource->postsCount(),
            'favorite'                => $favorite,
        ];
    }

    public static function jsonSchema(): array
    {
        return [
            'type'                 => ['object'],
            'properties'           => [
                'id'                      => ['type' => ['string']],
                'status'                  => ['type' => ['string', 'null']],
                'series'                  => SeriesResource::jsonSchema(),
                'model'                   => ['type' => ['string']],
                'logo'                    => ['type' => ['string']],
                'image'                   => ['type' => ['string', 'null']],
                'call_group_tags'         => ['type' => ['string', 'null']],
                'calling_groups'          => ['type' => ['string', 'null']],
                'type'                    => ['type' => ['string', 'null']],
                'model_description'       => ['type' => ['string', 'null']],
                'model_notes'             => ['type' => ['string', 'null']],
                'tonnage'                 => ['type' => ['number', 'null']],
                'total_circuits'          => ['type' => ['integer', 'null']],
                'dx_chiller'              => ['type' => ['string', 'null']],
                'cooling_type'            => ['type' => ['string', 'null']],
                'heating_type'            => ['type' => ['string', 'null']],
                'seer'                    => ['type' => ['string', 'null']],
                'eer'                     => ['type' => ['string', 'null']],
                'refrigerant'             => ['type' => ['string', 'null']],
                'original_charge_oz'      => ['type' => ['string', 'null']],
                'compressor_brand'        => ['type' => ['string', 'null']],
                'compressor_type'         => ['type' => ['string', 'null']],
                'compressor_model'        => ['type' => ['string', 'null']],
                'total_compressors'       => ['type' => ['integer', 'null']],
                'compressors_per_circuit' => ['type' => ['integer', 'null']],
                'compressor_sizes'        => ['type' => ['string', 'null']],
                'rla'                     => ['type' => ['string', 'null']],
                'lra'                     => ['type' => ['string', 'null']],
                'capacity_staging'        => ['type' => ['string', 'null']],
                'lowest_staging'          => ['type' => ['string', 'null']],
                'compressor_notes'        => ['type' => ['string', 'null']],
                'oil_type'                => ['type' => ['string', 'null']],
                'device_type'             => ['type' => ['string', 'null']],
                'devices_per_circuit'     => ['type' => ['integer', 'null']],
                'total_devices'           => ['type' => ['integer', 'null']],
                'device_size'             => ['type' => ['string', 'null']],
                'metering_device_notes'   => ['type' => ['string', 'null']],
                'fan_type'                => ['type' => ['string', 'null']],
                'cfm_range'               => ['type' => ['string', 'null']],
                'fan_notes'               => ['type' => ['string', 'null']],
                'voltage_phase_hz'        => ['type' => ['string', 'null']],
                'conversion_job'          => ['type' => ['string', 'null']],
                'bid_type'                => ['type' => ['string', 'null']],
                'man_hours'               => ['type' => ['number', 'null']],
                'charge_lbs'              => ['type' => ['number', 'null']],
                'exv'                     => ['type' => ['string', 'null']],
                'exv_qty'                 => ['type' => ['integer', 'null']],
                'exv_2'                   => ['type' => ['string', 'null']],
                'exv_2_qty'               => ['type' => ['integer', 'null']],
                'control_panel'           => ['type' => ['string', 'null']],
                'inspect'                 => ['type' => ['string', 'null']],
                'baseline'                => ['type' => ['string', 'null']],
                'airflow_waterflow'       => ['type' => ['string', 'null']],
                'recover'                 => ['type' => ['string', 'null']],
                'controls'                => ['type' => ['string', 'null']],
                'replace_install'         => ['type' => ['string', 'null']],
                'leak_check'              => ['type' => ['string', 'null']],
                'evacuate'                => ['type' => ['string', 'null']],
                'charge'                  => ['type' => ['string', 'null']],
                'tune'                    => ['type' => ['string', 'null']],
                'verify'                  => ['type' => ['string', 'null']],
                'label'                   => ['type' => ['string', 'null']],
                'conversion_notes'        => ['type' => ['string', 'null']],
                'date_added'              => ['type' => ['string', 'null']],
                'qa'                      => ['type' => ['string', 'null']],
                'qa_qc_comments'          => ['type' => ['string', 'null']],
                'last_qc_date'            => ['type' => ['string', 'null']],
                'info_source'             => ['type' => ['string', 'null']],
                'source'                  => ['type' => ['string', 'null']],
                'match'                   => ['type' => ['string', 'null']],
                'syncing_notes'           => ['type' => ['string', 'null']],
                'layout'                  => ['type' => ['object', 'null']],
                'tags'                    => TagCollection::jsonSchema(),
                'manuals'                 => ManualsResource::jsonSchema(),
                'conversions'             => ConversionJobsResource::jsonSchema(),
                'warnings'                => WarningCollection::jsonSchema(),
                'functional_parts_count'  => ['type' => ['integer']],
                'posts_count'             => ['type' => ['integer']],
                'favorite'                => ['type' => ['boolean']],
            ],
            'required'             => [
                'id',
                'status',
                'series',
                'model',
                'logo',
                'image',
                'type',
                'model_description',
                'model_notes',
                'tonnage',
                'total_circuits',
                'dx_chiller',
                'cooling_type',
                'heating_type',
                'seer',
                'eer',
                'refrigerant',
                'original_charge_oz',
                'compressor_brand',
                'compressor_type',
                'compressor_model',
                'total_compressors',
                'compressors_per_circuit',
                'compressor_sizes',
                'rla',
                'lra',
                'capacity_staging',
                'lowest_staging',
                'compressor_notes',
                'oil_type',
                'device_type',
                'devices_per_circuit',
                'total_devices',
                'device_size',
                'metering_device_notes',
                'fan_type',
                'cfm_range',
                'fan_notes',
                'voltage_phase_hz',
                'conversion_job',
                'bid_type',
                'man_hours',
                'charge_lbs',
                'exv',
                'exv_qty',
                'exv_2',
                'exv_2_qty',
                'control_panel',
                'inspect',
                'baseline',
                'airflow_waterflow',
                'recover',
                'controls',
                'replace_install',
                'leak_check',
                'evacuate',
                'charge',
                'tune',
                'verify',
                'label',
                'conversion_notes',
                'date_added',
                'qa',
                'qa_qc_comments',
                'last_qc_date',
                'info_source',
                'source',
                'match',
                'syncing_notes',
                'layout',
                'tags',
                'manuals',
                'conversions',
                'warnings',
                'functional_parts_count',
                'posts_count',
                'favorite',
            ],
            'additionalProperties' => false,
        ];
    }
}
