apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-test
  template:
    metadata:
      labels:
        app: laravel-test
    spec:
      containers:
      - image: us-west2-docker.pkg.dev/bluon-platform-dev/docker/laravel-test:latest
        name: laravel-test
    readinessProbe:
     httpGet:
     path: "/health-check"
     port: 8000
     initialDelaySeconds: 10
     timeoutSeconds: 5  
