apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-test
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /*
          backend:
            serviceName: laravel-test
            servicePort: 80
        - path: /*
          backend:
            serviceName: laravel-test
            servicePort: 80
