apiVersion: networking.k8s.io/v1
kind: Ingress   
metadata:   
  name: ingress-test 
spec:  
  defaultBackend:
    service:
      name: laravel-test
      port:
        number: 80
  rules:  
    - http:   
        paths:   
          - path: /   
            pathType: Prefix
            backend:   
              service:   
                name: laravel-test   
                port:   
                  number: 80
