apiVersion: networking.k8s.io/v1
kind: Ingress   
metadata:   
  name: ingress-test 
spec:  
  rules: 
    - host: test.bluontoolbox.com
      http:   
        paths:   
          - path: /*   
            pathType: ImplementationSpecific
            backend:   
              service:   
              name: laravel-test   
              port:   
                number: 80
