apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-dev
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: laravel-dev
  template:
    metadata:
      labels:
        app: laravel-dev
    spec:
      containers:
      - image: us-west2-docker.pkg.dev/bluon-platform-dev/docker/laravel-test:latest
        name: laravel-dev
        ports:
        - containerPort: 80