apiVersion: networking.k8s.io/v1
kind: Ingress   
metadata:   
  name: ingress-test   
  annotations:    
  labels:
    app: laravel  
spec:  
  rules: 
   - host: laraveltesting.com
     http:   
        paths:   
          - path: /*   
            pathType: ImplementationSpecific
            backend:   
              service:   
                name: laravel-test   
                port:   
                  number: 80
