apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-test
  namespace: test
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: laravel.local
      http:
      paths:
        - path: /*
           pathType: Prefix
            backend:
              service:
                name: laravel-test
                port:
                  number: 80
