apiVersion: v1
kind: Service
metadata:
  name: laravel-test
  annotations:
    cloud.google.com/backend-config: '{"ports": {"8000":"my-backendconfig"}}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  ports:
  - port: 8000    
    protocol: TCP
    targetPort: 8000
  selector:
    app: laravel-test
