apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-dev
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: laravel-dev
  template:
    metadata:
      labels:
        app: laravel-dev
    spec:
      containers:
      - image: mysql:8.0.26
        name: laravel-dev
        ports:
        - containerPort: 80