apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-dev
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: laravel-dev
  template:
    metadata:
      labels:
        app: laravel-dev
    spec:
      containers:
      - image: mysql:8.0.26
        name: laravel-dev
        env:
         - name: laravel-dev
           MYSQL_DATABASE: test
           MYSQL_HOST: 127.0.0.1
           MYSQL_PASSWORD: root
           MYSQL_ROOT_PASSWORD: pas
        ports:
        - containerPort: 80