<?php

namespace Database\Seeders\SOP;

use App\Models\ModelType;
use App\Models\Oem;
use Illuminate\Support\Collection;

class OemGenerator
{
    private Collection $oems;
    private Collection $series;
    const OEMS = [
        [
            "uuid"              => "03BB4819-7F61-41BA-9E11-60BA19543C42",
            "status"            => "Live",
            "model"             => "BP078C00B2CAA3A",
            "logo"              => "https://dl.airtable.com/.attachments/2923b4957dfeea19823f724cd8c6192e/ac21bccd/york.png",
            "unit_image"        => "https://dl.airtable.com/.attachments/8fc097cf26423bdb502bb070e4d83363/4b013819/york_bpo.png",
            "model_type"        => "Package Unit",
            "new_system_type"   => "Package Unit (HP)",
            "forum_tag"         => "Package Unit",
            "model_description" => "6.5 TON SINGLE PACKAGE HEAT PUMP",
            "model_notes"       => "208-230V, 3PH, 60HZ",
            "show_parts"        => 1,
            "product_data"      => "https://dl.airtable.com/.attachments/99e2e524cbef2f08751e6d4cecd3d893/6722f720/YO_BP_6.5-12.5PkgHP_TG_R22_2009.pdf",
            "iom"               => "https://dl.airtable.com/.attachments/b66ecbfd4052854a09e8107108b0bc3a/38bf1209/YO_BP_6_5-12_5PkgHP_IM_R22_2006.pdf",
            "wiring_diagram"    => "https://dl.airtable.com/.attachments/b80394fb61898df6f898e57a1efa0e99/a2bc3501/PagesfromYO_BP_6.5-12.5PkgHP_TG_R22_2009.pdf;https://dl.airtable.com/.attachments/c1ed8c4ac639279094e5ea0cc4f1d2cb/38a70526/PagesfromYO_BP_6_5-12_5PkgHP_IM_R22_2006.pdf",
            "tonnage"           => 7,
            "total_circuits"    => 1,
            "refrigerant"       => "R-22",
            "voltage_phase_hz"  => "208-230/3/60",
            "conversion_job"    => "GREEN",
            "bid_type"          => "Standard",
            "info_source"       => "035-19238-001 A",
            "source"            => "merged",
            "match"             => "merged with BP078****2",
            "series_name"       => 'BP',
        ],
        [
            "uuid"              => "0C8FE34C-6783-4924-9369-86925F9581DB",
            "status"            => "Live",
            "model"             => "TWX024C100A0",
            "logo"              => "https://dl.airtable.com/e8HaFlEgQteGguw4oGGA_trane.png",
            "unit_image"        => "https://dl.airtable.com/.attachments/79b015e69e33ce70ab2ca199f3c21666/3b333eba/TWXImage.JPG",
            "model_type"        => "Condenser",
            "new_system_type"   => "Heat Pump Condenser",
            "forum_tag"         => "Condenser",
            "model_description" => "SPLIT SYSTEM HEAT PUMP",
            "show_parts"        => 1,
            "service_facts"     => "https://dl.airtable.com/.attachments/443409e94f02dd0901995a8754949c6c/b41f6004/Trane_TWX_024SplitHP_1Phase_SF_R22_1996.pdf",
            "product_data"      => "https://dl.airtable.com/.attachments/995bc8af545e1ce12baf61f0ce4ef3cb/be606e31/Trane_TWX_018-060SplitHP_1Phase_PD_R22_2001.pdf",
            "tonnage"           => 2,
            "total_circuits"    => 1,
            "refrigerant"       => "R-22",
            "voltage_phase_hz"  => "208-230/1/60",
            "conversion_job"    => "GREEN",
            "bid_type"          => "Standard",
            "info_source"       => "TWX-UP-5A",
            "source"            => "merged",
            "match"             => "merged with TWX024C1",
            "series_name"       => 'D*CG',
        ],
        [
            "uuid"              => "11835364-55FE-4BBF-99B0-BA653D6DCCBE",
            "status"            => "Live",
            "model"             => "D7CG060N09925A",
            "logo"              => "https://dl.airtable.com/.attachments/2923b4957dfeea19823f724cd8c6192e/ac21bccd/york.png",
            "unit_image"        => "https://dl.airtable.com/.attachments/4bbdc98c56b2c31c500b303055eb9f9f/a1c469c3/D4CEImage.PNG",
            "model_type"        => "Package Unit",
            "new_system_type"   => "Package Unit (Outdoor)",
            "forum_tag"         => "Package Unit",
            "model_description" => "SINGLE PACKAGE GAS - ELECTRIC",
            "show_parts"        => 1,
            "product_data"      => "https://dl.airtable.com/.attachments/7b2a798252bf6686947ff40e9d7f1757/78da14e5/d2cg_072_PD.pdf",
            "iom"               => "https://dl.airtable.com/.attachments/61be8c6ed36d8dc9203bc9b825474d60/5db7ef79/d2cg_072_installation_instruction-1.pdf",
            "tonnage"           => 5,
            "total_circuits"    => 1,
            "refrigerant"       => "R-22",
            "voltage_phase_hz"  => "208-230/3/60",
            "conversion_job"    => "GREEN",
            "bid_type"          => "Standard",
            "info_source"       => "530.18-RP9.4Y",
            "source"            => "merged",
            "match"             => "merged with D7CG060N09925",
            "series_name"       => 'B*HZ',
        ],
        [
            "uuid"              => "1AF24BF4-409D-4361-B5D7-4781B8F6A6E7",
            "status"            => "Live",
            "model"             => "RLMB-A102CL010",
            "logo"              => "https://dl.airtable.com/eo399CIXRYWaCelLFMJW_rheem.png",
            "unit_image"        => "https://dl.airtable.com/.attachments/7cac920728756840e6cc331ec27c42a6/e2e8ea87/RLKBImage.PNG",
            "model_type"        => "Package Unit",
            "new_system_type"   => "Package Unit (Outdoor)",
            "forum_tag"         => "Package Unit",
            "model_description" => "12 SEER HIGH EFF COMMERCIAL PACKAGED A/C",
            "model_notes"       => "208-230V, 3PH",
            "show_parts"        => 1,
            "product_data"      => "https://dl.airtable.com/.attachments/1ed8dcb23822224b1b74f4e191cd789d/4788e10b/RLKBPD.pdf",
            "tonnage"           => 9,
            "total_circuits"    => 2,
            "refrigerant"       => "R-22",
            "voltage_phase_hz"  => "208-230/3/60",
            "conversion_job"    => "GREEN",
            "bid_type"          => "Standard",
            "info_source"       => "92-42800-RLMB",
            "source"            => "merged",
            "match"             => "merged with RLMB-A102CL",
            "series_name"       => 'TWX0',
        ],
        [
            "uuid"              => "C8C742DB-571F-43C0-99D0-45ACED515807",
            "status"            => "Live",
            "model"             => "RLMB-A240YM075",
            "logo"              => "https://dl.airtable.com/eo399CIXRYWaCelLFMJW_rheem.png",
            "unit_image"        => "https://dl.airtable.com/kfIDQsWBR2iKHAsL7m6p_RH_004.PNG",
            "model_type"        => "Package Unit",
            "new_system_type"   => "Package Unit (Outdoor)",
            "forum_tag"         => "Package Unit",
            "model_description" => "12 SEER HIGH EFF COMMERCIAL PACKAGED A/C",
            "model_notes"       => "575V, 3PH",
            "show_parts"        => 1,
            "product_data"      => "https://dl.airtable.com/v99g9z9uREKfX8A69VC9_Rheem_RLKB%20RLMB%20RLNB_15%20TO%2025%20TON_Package%20GE.pdf",
            "tonnage"           => 20,
            "total_circuits"    => 2,
            "refrigerant"       => "R-22",
            "voltage_phase_hz"  => "575/3/60",
            "conversion_job"    => "GREEN",
            "bid_type"          => "Standard",
            "info_source"       => "92-42800-RLMB",
            "source"            => "merged",
            "match"             => "merged with RLMB-A240YM",
            "series_name"       => 'TWX0',
        ],
        [
            "uuid"              => "264266BB-7A2F-4C56-9829-CF64CE0CE986",
            "status"            => "Live",
            "model"             => "RJMA-A042DK024",
            "logo"              => "https://dl.airtable.com/eo399CIXRYWaCelLFMJW_rheem.png",
            "unit_image"        => "https://dl.airtable.com/F8SRmHlSb61Jj1CKQTDN_RH_001.PNG",
            "model_type"        => "Package Unit",
            "new_system_type"   => "Package Unit (HP)",
            "forum_tag"         => "Package Unit",
            "model_description" => "12 SEER HIGH EFF PACKAGED HEAT PUMP",
            "model_notes"       => "460-3-50, COMP ID 5590",
            "show_parts"        => 1,
            "product_data"      => "https://dl.airtable.com/OldLx9XR62NTjfwcfGrA_Rheem_RJKA%20RJMA%20024-60_Product%20Info.pdf",
            "tonnage"           => 4,
            "total_circuits"    => 1,
            "refrigerant"       => "R-22",
            "voltage_phase_hz"  => "460/3/60",
            "conversion_job"    => "GREEN",
            "bid_type"          => "Standard",
            "info_source"       => "92-42800-RJMA",
            "source"            => "merged",
            "match"             => "merged with RJMA-A042DK",
            "series_name"       => 'Voyager',
        ],
        [
            "uuid"              => "6766279C-E211-4203-B8A8-5E1E698B5ED1",
            "status"            => "Live",
            "model"             => "RJMA-A060CL020",
            "logo"              => "https://dl.airtable.com/eo399CIXRYWaCelLFMJW_rheem.png",
            "unit_image"        => "https://dl.airtable.com/F8SRmHlSb61Jj1CKQTDN_RH_001.PNG",
            "model_type"        => "Package Unit",
            "new_system_type"   => "Package Unit (HP)",
            "forum_tag"         => "Package Unit",
            "model_description" => "12 SEER HIGH EFF PACKAGED HEAT PUMP",
            "model_notes"       => "208-230-3, COMP ID 5717",
            "show_parts"        => 1,
            "product_data"      => "https://dl.airtable.com/OldLx9XR62NTjfwcfGrA_Rheem_RJKA%20RJMA%20024-60_Product%20Info.pdf",
            "tonnage"           => 5,
            "total_circuits"    => 1,
            "refrigerant"       => "R-22",
            "voltage_phase_hz"  => "208-230/3/60",
            "conversion_job"    => "GREEN",
            "bid_type"          => "Standard",
            "info_source"       => "92-42800-RJMA",
            "source"            => "merged",
            "match"             => "merged with RJMA-A060CL",
            "series_name"       => 'Voyager',
        ],
        [
            "uuid"              => "43924EDC-DF4B-4F5B-A2F8-5B2807FEB8E8",
            "status"            => "Live",
            "model"             => "38BRG042320",
            "logo"              => "https://dl.airtable.com/J8IV22NATS6wCtZDzPMu_carrier.png",
            "unit_image"        => "https://dl.airtable.com/ryTzexikQpGZd7FADcGN_CR_008.PNG",
            "model_type"        => "Condenser",
            "new_system_type"   => "Condensing Unit",
            "forum_tag"         => "Condenser",
            "model_description" => "12 SEER SPLIT SYSTEM AIR CONDITIONER",
            "model_notes"       => "208-230V, 1PH, 60HZ",
            "show_parts"        => 1,
            "product_data"      => "https://dl.airtable.com/1S867FHcRviyaErqx1ul_12StraightCoolCondensing38BRG.pdf",
            "tonnage"           => 4,
            "total_circuits"    => 1,
            "refrigerant"       => "R-22",
            "voltage_phase_hz"  => "208-230/1/60",
            "conversion_job"    => "GREEN",
            "bid_type"          => "Standard",
            "source"            => "merged",
            "match"             => "merged with 38BRG04232",
            "series_name"       => 'TWP0',
        ],
        [
            "uuid"              => "4A60568E-06E2-4967-8B82-C52D365097C3",
            "status"            => "Live",
            "model"             => "48TCDM08---5A",
            "logo"              => "https://dl.airtable.com/J8IV22NATS6wCtZDzPMu_carrier.png",
            "unit_image"        => "https://dl.airtable.com/.attachments/c88b1f8cad37641bf84b86eba2807bb6/e2784bd9/48TCPIC.png",
            "model_type"        => "Package Unit",
            "new_system_type"   => "Package Unit (Outdoor)",
            "forum_tag"         => "Package Unit",
            "model_description" => "7.5 TON PACKAGED ROOFTOP GAS HEAT & ELECTRIC COOLING UNIT, 208-230V 3PH 60HZ",
            "model_notes"       => "48TCDM085A",
            "show_parts"        => 1,
            "service_facts"     => "https://dl.airtable.com/.attachments/7b217cc9290c599433f0304e31b0da4e/dba52cc4/CR_48TC4-16_48TC-4-16-01SM_SM.pdf",
            "product_data"      => "https://dl.airtable.com/.attachments/8560a7050e761b7739c95f972ee9121c/dd070172/CR_PD_48TC-7-16-03PD_2020.pdf",
            "iom"               => "https://dl.airtable.com/.attachments/1d4f9f65b300fde2e131841b4983a281/3fbbe7bf/CR_TC_II_48TC-7-16-02SI_2020.pdf",
            "wiring_diagram"    => "https://dl.airtable.com/.attachments/5a9e23ae849292652edca2dbf3609831/ee73e24a/CR_48TC_WD.pdf",
            "tonnage"           => 8,
            "total_circuits"    => 1,
            "refrigerant"       => "R-410A",
            "voltage_phase_hz"  => "208-230/3/60",
            "conversion_job"    => "R410A",
            "bid_type"          => "N/A - R410A",
            "info_source"       => "AQ-CARE-2106",
            "source"            => "merged",
            "match"             => "merged with 48TCDM08***5",
            "series_name"       => 'RLMB',
        ],
        [
            "uuid"              => "4EFF39EA-6B79-4C76-8D80-2C8F345A503D",
            "status"            => "Live",
            "model"             => "YCD211B3LGCA",
            "logo"              => "https://dl.airtable.com/e8HaFlEgQteGguw4oGGA_trane.png",
            "unit_image"        => "https://dl.airtable.com/HosVTGWQTA6YAO5Q9GVS_TR_009.PNG",
            "model_type"        => "Package Unit",
            "new_system_type"   => "Package Unit (Outdoor)",
            "forum_tag"         => "Package Unit",
            "model_description" => "PACKAGED GAS - ELECTRIC",
            "show_parts"        => 1,
            "product_data"      => "https://dl.airtable.com/YaoaVymdTidBnczjwl98_rtprc024en_12.08.06.pdf",
            "iom"               => "https://dl.airtable.com/.attachments/f9f2374a98f381d8c54143e394a44e9d/a5fb73f2/YCDIOM2007.PDF",
            "tonnage"           => 18,
            "total_circuits"    => 2,
            "refrigerant"       => "R-22",
            "voltage_phase_hz"  => "208-230/3/60",
            "conversion_job"    => "GREEN",
            "bid_type"          => "Standard",
            "info_source"       => "YCD-UP-133",
            "source"            => "merged",
            "match"             => "merged with YCD211*3",
            "series_name"       => 'RJMA',
        ],
        [
            "uuid"              => "5F2E4E93-1F29-4F83-B3E4-6C46C16AB085",
            "status"            => "Live",
            "model"             => "WCH180B40FCA",
            "logo"              => "https://dl.airtable.com/e8HaFlEgQteGguw4oGGA_trane.png",
            "unit_image"        => "https://dl.airtable.com/yz67rhitQf23C6gBS7Df_TR_007.PNG",
            "model_type"        => "Package Unit",
            "new_system_type"   => "Package Unit (HP)",
            "forum_tag"         => "Package Unit",
            "model_description" => "PACKAGED HEAT PUMP",
            "show_parts"        => 1,
            "service_facts"     => "https://dl.airtable.com/.attachments/928cc84653947e31c1e0b59f0305bce2/1c219a07",
            "product_data"      => "https://dl.airtable.com/lHxszy3QSln9axNGd6pQ_pkgpprc001enr1.pdf",
            "iom"               => "https://dl.airtable.com/.attachments/2b8975ed1121320d7c7ed9985a698919/f1cb10d5",
            "tonnage"           => 15,
            "total_circuits"    => 2,
            "refrigerant"       => "R-22",
            "voltage_phase_hz"  => "480/3/60",
            "conversion_job"    => "GREEN",
            "bid_type"          => "Standard",
            "info_source"       => "WCH-UP-54",
            "source"            => "merged",
            "match"             => "merged with WCH180*4",
            "series_name"       => 'RJMA',
        ],
        [
            "uuid"              => "756BA061-7E3F-49CE-959E-66EEEA51FCE2",
            "status"            => "Live",
            "model"             => "TCD150B300BA",
            "logo"              => "https://dl.airtable.com/e8HaFlEgQteGguw4oGGA_trane.png",
            "unit_image"        => "https://dl.airtable.com/HosVTGWQTA6YAO5Q9GVS_TR_009.PNG",
            "model_type"        => "Package Unit",
            "new_system_type"   => "Package Unit (Outdoor)",
            "forum_tag"         => "Package Unit",
            "model_description" => "DOWNFLOW COOLING PACKAGE",
            "model_notes"       => "208-230V, 3PH, 12-1/2 TON",
            "show_parts"        => 1,
            "service_facts"     => "https://dl.airtable.com/.attachments/e462c1351539d7d359a59a672a88c8c6/c152de85",
            "product_data"      => "https://dl.airtable.com/uykgioi6RDeHW5yQP2tm_rtprc002en_r4.pdf",
            "iom"               => "https://dl.airtable.com/.attachments/b71d4a175da8d4d3f1daf6357292b502/c05388b7",
            "misc"              => "https://dl.airtable.com/.attachments/2481a3f0ac324191c0e6abed15853446/64c87e1d",
            "tonnage"           => 13,
            "total_circuits"    => 2,
            "refrigerant"       => "R-22",
            "voltage_phase_hz"  => "208-230/3/60",
            "conversion_job"    => "GREEN",
            "bid_type"          => "Standard",
            "info_source"       => "TCD-UP-55A",
            "source"            => "merged",
            "match"             => "merged with TCD150*3",
            "series_name"       => 'RJMA',
        ],
        [
            "uuid"              => "51096C38-2AF8-4F4C-89C6-7E7F5BD97984",
            "status"            => "Live",
            "model"             => "TWP036C300A1",
            "logo"              => "https://dl.airtable.com/e8HaFlEgQteGguw4oGGA_trane.png",
            "unit_image"        => "https://dl.airtable.com/.attachments/bc7d9275e379a880f826197417ce5971/2878a8d0/TWP.JPG",
            "model_type"        => "Condenser",
            "new_system_type"   => "Heat Pump Condenser",
            "forum_tag"         => "Condenser",
            "model_description" => "SPLIT-SYSTEM HEAT PUMP",
            "show_parts"        => 1,
            "service_facts"     => "https://dl.airtable.com/.attachments/b2b00cdde4a4e8cb8807d1a7e16b0cff/900aa03b/Trane_TWP_036SplitHP_208-2303Phase_SF_R22_1999.pdf",
            "product_data"      => "https://dl.airtable.com/.attachments/9c60e5086eea7c0fd1276981e00e4d88/4917bc31/Trane_TWP_030-060SplitHP_3Phase_PD_R22_2000.pdf",
            "misc"              => "https://dl.airtable.com/.attachments/fa7fcf9f65a189ead8195413a81e31a6/08036446/Trane_TWP_036SplitHP_3Phase_Submittal_R22_2000.pdf",
            "tonnage"           => 3,
            "total_circuits"    => 1,
            "refrigerant"       => "R-22",
            "voltage_phase_hz"  => "208-230/3/60",
            "conversion_job"    => "GREEN",
            "bid_type"          => "Standard",
            "info_source"       => "TWP-UP-6",
            "source"            => "merged",
            "match"             => "merged with TWP036C3",
            "series_name"       => 'RJNA',
        ],
        [
            "uuid"              => "717AA821-0420-4CAB-861C-1B73F9733709",
            "status"            => "Live",
            "model"             => "48SD-048115500",
            "logo"              => "https://dl.airtable.com/J8IV22NATS6wCtZDzPMu_carrier.png",
            "unit_image"        => "https://dl.airtable.com/w9GhS4WRQOTEF3NkhyEh_CR_012.PNG",
            "model_type"        => "Package Unit",
            "new_system_type"   => "Package Unit (Outdoor)",
            "forum_tag"         => "Package Unit",
            "model_description" => "SINGLE-PACKAGE GAS HEATING ELECTRIC COOLING UNIT",
            "model_notes"       => "48SD048115500",
            "show_parts"        => 1,
            "product_data"      => "https://dl.airtable.com/5GoEK2sAQ2Gq46YDiZOY_48sd-2pd.pdf",
            "tonnage"           => 4,
            "total_circuits"    => 1,
            "refrigerant"       => "R-22",
            "voltage_phase_hz"  => "208-230/3/60",
            "conversion_job"    => "GREEN",
            "bid_type"          => "Standard",
            "info_source"       => "BT-329-1804",
            "source"            => "merged",
            "match"             => "merged with 48SD-0481155",
            "series_name"       => 'RRKA-A',
        ],
        [
            "uuid"              => "8C1881B9-4495-4D58-ABB9-DAA0BB13530C",
            "status"            => "Live",
            "model"             => "RJNA-A042CM020",
            "logo"              => "https://dl.airtable.com/eo399CIXRYWaCelLFMJW_rheem.png",
            "unit_image"        => "https://dl.airtable.com/t4bjr1EoQXMdEADxtfHt_RH_002.png",
            "model_type"        => "Package Unit",
            "new_system_type"   => "Package Unit (HP)",
            "forum_tag"         => "Package Unit",
            "model_description" => "13 SEER COMMERCIAL PACKAGED HEAT PUMP 208-230V 3PH 60HZ",
            "show_parts"        => 1,
            "product_data"      => "https://dl.airtable.com/ZpitvzJ7QrWbtw8qGWuj_Rheem%20RJNA%20package%20unit.pdf",
            "tonnage"           => 4,
            "total_circuits"    => 1,
            "refrigerant"       => "R-22",
            "voltage_phase_hz"  => "208-230/3/60",
            "conversion_job"    => "GREEN",
            "bid_type"          => "Standard",
            "info_source"       => "92-42800-RJNA",
            "source"            => "merged",
            "match"             => "merged with RJNA-A042CM",
            "series_name"       => 'RKNB',
        ],
        [
            "uuid"              => "B2963F2B-E1A5-4B76-8E28-3C1638973EEE",
            "status"            => "Live",
            "model"             => "RRKA-A048CK06E",
            "logo"              => "https://dl.airtable.com/eo399CIXRYWaCelLFMJW_rheem.png",
            "unit_image"        => "https://dl.airtable.com/c2IcuVaTZ57I0z5T2scw_RH_012.png",
            "model_type"        => "Package Unit",
            "new_system_type"   => "Package Unit (Outdoor)",
            "forum_tag"         => "Package Unit",
            "model_description" => "PACKAGED GAS ELECTRIC ROOFTOP UNIT",
            "model_notes"       => "COMP 6021, GAS CODE 1D",
            "show_parts"        => 1,
            "product_data"      => "https://dl.airtable.com/knhMRb2QTH2UPq0h4m8J_Rheem_RRNA%20036-60.pdf",
            "tonnage"           => 4,
            "total_circuits"    => 1,
            "refrigerant"       => "R-22",
            "voltage_phase_hz"  => "208-230/3/60",
            "conversion_job"    => "GREEN",
            "bid_type"          => "Standard",
            "info_source"       => "92-42800-RRKA-A",
            "source"            => "merged",
            "match"             => "merged with RRKA-A048CK",
            "series_name"       => '38BRG',
        ],
        [
            "uuid"              => "CC5189EC-A24E-4566-A121-C2E4EF418CA2",
            "status"            => "Live",
            "model"             => "RKNB-A102CM15E",
            "logo"              => "https://dl.airtable.com/eo399CIXRYWaCelLFMJW_rheem.png",
            "unit_image"        => "https://dl.airtable.com/I3HNxNXWQ5ONJJK1vg3L_RH_009.PNG",
            "model_type"        => "Package Unit",
            "new_system_type"   => "Package Unit (Outdoor)",
            "forum_tag"         => "Package Unit",
            "model_description" => "13 SEER COMM PACKAGE GAS ELEC ROOFTOP",
            "model_notes"       => "GAS CODE 2D COMP ID 7073",
            "show_parts"        => 1,
            "product_data"      => "https://dl.airtable.com/1PChPnGTyWDYTB8h380k_R11-833_Rev_2.pdf",
            "tonnage"           => 9,
            "total_circuits"    => 2,
            "refrigerant"       => "R-22",
            "voltage_phase_hz"  => "208-230/3/60",
            "conversion_job"    => "GREEN",
            "bid_type"          => "Standard",
            "info_source"       => "92-42800-RKNB",
            "source"            => "merged",
            "match"             => "merged with RKNB-A102CM",
            "series_name"       => '48TC',
        ],
        [
            "uuid"              => "EBD00DF9-27E0-4926-ADA4-802A0793A796",
            "status"            => "Live",
            "model"             => "48HJE014---180",
            "logo"              => "https://dl.airtable.com/J8IV22NATS6wCtZDzPMu_carrier.png",
            "unit_image"        => "https://dl.airtable.com/ZcMr0RJsThmNYTfnkoEx_CR_047.PNG",
            "model_type"        => "Package Unit",
            "new_system_type"   => "Package Unit (Outdoor)",
            "forum_tag"         => "Package Unit",
            "model_description" => "GAS HEATING/ELEC.COOLING SINGLE PACKAGED ROOFTOP",
            "model_notes"       => "48HJE014180",
            "show_parts"        => 1,
            "product_data"      => "https://dl.airtable.com/HQKJIRe5Ra6nyorotaP4_48H_2-25TonPckg_PD_R22_2006.pdf",
            "iom"               => "https://dl.airtable.com/.attachments/d12b8811c0bd8ad60d6f55848a332097/8fbc92fa/48HJ-32SI-1IOM.pdf",
            "diagnostic"        => "https://dl.airtable.com/.attachments/cb3c686e9c7b596f8267f4eb5cca88ae/62b423e3/48HJ-32SI-1IOMERROR-FLASHCODES.pdf;https://dl.airtable.com/.attachments/95c5858988b8d656ea4ef1966a57790b/125abf5b/48HJ-32SI-1IOMTROUBLESHOOTING.pdf",
            "wiring_diagram"    => "https://dl.airtable.com/.attachments/46e7eb64ca30feedabffd381ca2e1295/713cdb5f/PagesfromHQKJIRe5Ra6nyorotaP4_48H_2-25TonPckg_PD_R22_2006.pdf;https://dl.airtable.com/.attachments/2084d2aa0a6efcced742eff69b8bb6d7/f964273f/PagesfromHQKJIRe5Ra6nyorotaP4_48H_2-25TonPckg_PD_R22_2006.pdf;https://dl.airtable.com/.attachments/c9bcc7de60af966544dbc6b31eea7f41/4e152633/Pagesfrom48HJ-32SI-1IOM-2.pdf",
            "tonnage"           => 13,
            "total_circuits"    => 2,
            "refrigerant"       => "R-22",
            "voltage_phase_hz"  => "575/3/60",
            "conversion_job"    => "GREEN",
            "bid_type"          => "Standard",
            "info_source"       => "BT-329-1804",
            "source"            => "merged",
            "match"             => "merged with 48HJE014***1",
            "series_name"       => '48SD',
        ],
        [
            "uuid"              => "F3CC58C2-FEEA-4126-9BAA-71D739868453",
            "status"            => "Live",
            "model"             => "B1HZ036A06A",
            "logo"              => "https://dl.airtable.com/.attachments/2923b4957dfeea19823f724cd8c6192e/ac21bccd/york.png",
            "unit_image"        => "https://dl.airtable.com/.attachments/95397e24b19d41df49843c94a8c9dabf/a5d63a65/B2HZIMAGE.jpg",
            "model_type"        => "Package Unit",
            "new_system_type"   => "Package Unit (HP)",
            "forum_tag"         => "Package Unit",
            "model_description" => "13 SEER SINGLE PACKAGE HEAT PUMP, 3TON",
            "model_notes"       => "208-230V, 1PH",
            "show_parts"        => 1,
            "service_facts"     => "https://dl.airtable.com/.attachments/262199e3a513957e378c501fee232339/9ebf3ad8/035-23152-001-A-0212_fm.pdf",
            "iom"               => "https://dl.airtable.com/.attachments/32b106e61736a9318c435966605a5e3b/2af65e14/B2HZ.pdf",
            "wiring_diagram"    => "https://dl.airtable.com/.attachments/39c8f659b5956843a9ee2fa1fc965fc1/04a89cd8/PagesfromB2HZ-2.pdf",
            "tonnage"           => 3,
            "total_circuits"    => 1,
            "refrigerant"       => "R-410A",
            "voltage_phase_hz"  => "208-230/1/60",
            "conversion_job"    => "R410A",
            "bid_type"          => "N/A - R410A",
            "qa_qc_comments"    => "12/27/2021 - NF - Need to change series",
            "info_source"       => "035-20210-000 A",
            "source"            => "merged",
            "match"             => "merged with B*HZ036A06",
            "series_name"       => '48HJE',
        ],
        [
            "uuid"              => "F3CC58C2-FEEA-4126-9BAA-71D739868464",
            "status"            => "Live",
            "model"             => "R4GE-X24K072X",
            "logo"              => "https://dl.airtable.com/uPdcrcFbTeygQwuVJ9Jw_miller.png",
            "unit_image"        => "https://dl.airtable.com/1yEueyWaQpKD8P7H1Evi_FG_009.png",
            "model_type"        => "Package Unit",
            "new_system_type"   => "Package Unit (Outdoor)",
            "forum_tag"         => "Package Unit",
            "model_description" => "14 SEER SINGLE PACKAGE GAS PACK",
            "model_notes"       => "208-230V, 1PH",
            "show_parts"        => 1,
            "product_data"      => "https://dl.airtable.com/MIoPo0mKRiW2Kvh6OOow_a377c.pdf",
            "tonnage"           => 2,
            "total_circuits"    => 1,
            "refrigerant"       => "R-410A",
            "voltage_phase_hz"  => "208-230/1/60",
            "conversion_job"    => "R410A",
            "bid_type"          => "N/A - R410A",
            "info_source"       => "7085950",
            "source"            => "merged",
            "match"             => "merged with R4GE-X24K",
            "series_name"       => 'R4GE',
        ],
    ];

    public function __construct(Collection $series)
    {
        $this->oems   = new Collection();
        $this->series = $series;
    }

    public function getOems(): Collection
    {
        return $this->oems;
    }

    public function createOems()
    {
        foreach (self::OEMS as $oemData) {
            $oem    = Oem::firstWhere('uuid', $oemData['uuid']);
            $series = $this->series->where('name', $oemData['series_name'])->first();
            if (!$oem && $series) {
                $oemFactory = Oem::factory()->usingSeries($series);
                $modelType  = ModelType::where('name', $oemData['model_type'])->first();
                if ($modelType) {
                    $oemFactory->usingModelType($modelType);
                }
                unset($oemData['series_name'], $oemData['model_type']);
                $oem = $oemFactory->create($oemData);
            }

            if ($oem) {
                $this->oems->push($oem);
            }
        }
    }
}
