apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
spec:
  destination:
    name: ''
    namespace: test
    server: 'https://kubernetes.default.svc'
  source:
    path: app-01
    repoURL: 'git@github.com:bionatus/test-app.git'
    targetRevision: HEAD
  project: default
