apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
spec:
  destination:
    name: ''
    namespace: test
    server: 'https://rancher.bluontoolbox.com/k8s/clusters/c-kqkxv'
  source:
    path: app-01
    repoURL: 'git@github.com:bionatus/test-app.git'
    targetRevision: HEAD
  project: default
