<?php

namespace App\Http\Resources\Models;

use App\Http\Resources\HasJsonSchema;
use App\Models\Motor;
use Illuminate\Http\Resources\Json\JsonResource;

/**
 * @property Motor $resource
 */
class MotorResource extends JsonResource implements HasJsonSchema
{
    public function __construct(Motor $resource)
    {
        parent::__construct($resource);
    }

    public function toArray($request)
    {
        return [
            'motor_type'               => $this->resource->motor_type,
            'duty_rating'              => $this->resource->duty_rating,
            'voltage'                  => $this->resource->voltage,
            'ph'                       => $this->resource->ph,
            'hz'                       => $this->resource->hz,
            'run_capacitor_size'       => $this->resource->run_capacitor_size,
            'start_capacitor_size'     => $this->resource->start_capacitor_size,
            'rpm'                      => $this->resource->rpm,
            'output_hp'                => $this->resource->output_hp,
            'frame_type'               => $this->resource->frame_type,
            'rotation'                 => $this->resource->rotation,
            'speed'                    => $this->resource->speed,
            'shaft_diameter'           => $this->resource->shaft_diameter,
            'shaft_keyway'             => $this->resource->shaft_keyway,
            'shaft_length'             => $this->resource->shaft_length,
            'shaft_type'               => $this->resource->shaft_type,
            'bearing_type'             => $this->resource->bearing_type,
            'fla'                      => $this->resource->fla,
            'mounting_type'            => $this->resource->mounting_type,
            'replaceable_bearings'     => $this->resource->replaceable_bearings,
            'motor_diameter'           => $this->resource->motor_diameter,
            'motor_height'             => $this->resource->motor_height,
            'enclosure_type'           => $this->resource->enclosure_type,
            'material_type'            => $this->resource->material_type,
            'weight'                   => $this->resource->weight,
            'protection'               => $this->resource->protection,
            'rla'                      => $this->resource->rla,
            'lra'                      => $this->resource->lra,
            'service_factor'           => $this->resource->service_factor,
            'power_factor'             => $this->resource->power_factor,
            'cfm'                      => $this->resource->cfm,
            'efficiency'               => $this->resource->efficiency,
            'alternate_part_numbers'   => $this->resource->alternate_part_numbers,
            'output_watts'             => $this->resource->output_watts,
            'input_watts'              => $this->resource->input_watts,
            'ring_size'                => $this->resource->ring_size,
            'resilient_ring_dimension' => $this->resource->resilient_ring_dimension,
            'armature_amps'            => $this->resource->armature_amps,
            'field_amps'               => $this->resource->field_amps,
            'service_factor_amps'      => $this->resource->service_factor_amps,
            'multi_voltage'            => $this->resource->multi_voltage,
            'rotation_orientation'     => $this->resource->rotation_orientation,
            'mounting_angle'           => $this->resource->mounting_angle,
            'conduit_box_orientation'  => $this->resource->conduit_box_orientation,
            'torque_type'              => $this->resource->torque_type,
            'drive_type'               => $this->resource->drive_type,
            'misc'                     => $this->resource->misc,
            'armature_voltage'         => $this->resource->armature_voltage,
            'field_voltage'            => $this->resource->field_voltage,
            'start_type'               => $this->resource->start_type,
            'output_voltage'           => $this->resource->output_voltage,
            'trademark_name'           => $this->resource->trademark_name,
            'module_part_number'       => $this->resource->module_part_number,
            'included_with'            => $this->resource->included_with,
            'operating_temperature'    => $this->resource->operating_temperature,
            'electrical_notes'         => $this->resource->electrical_notes,
            'constant_torque_speed'    => $this->resource->constant_torque_speed,
            'variable_torque_speed'    => $this->resource->variable_torque_speed,
            'start_torque'             => $this->resource->start_torque,
            'run_torque'               => $this->resource->run_torque,
            'full_load_torque'         => $this->resource->full_load_torque,
            'load_factor'              => $this->resource->load_factor,
            'frame_diameter'           => $this->resource->frame_diameter,
            'cooling_type'             => $this->resource->cooling_type,
            'notes'                    => $this->resource->notes,
            'a_dimension'              => $this->resource->a_dimension,
            'b_dimension'              => $this->resource->b_dimension,
            'total_length'             => $this->resource->total_length,
            'efficiency_type'          => $this->resource->efficiency_type,
            'shaft_dimensions'         => $this->resource->shaft_dimensions,
            'fan_blade_dimensions'     => $this->resource->fan_blade_dimensions,
            'stack'                    => $this->resource->stack,
            'part_type'                => $this->resource->part_type,
            'lead_length'              => $this->resource->lead_length,
            'capacitor_part_number'    => $this->resource->capacitor_part_number,
            'eisa_rating'              => $this->resource->eisa_rating,
            'bissc_rating'             => $this->resource->bissc_rating,
            'shaft_orientation'        => $this->resource->shaft_orientation,
            'run_type'                 => $this->resource->run_type,
            'number_of_poles'          => $this->resource->number_of_poles,
            'correct_part_number'      => $this->resource->correct_part_number,
            'mount_part_number'        => $this->resource->mount_part_number,
            'iec_rating'               => $this->resource->iec_rating,
            'braking_torque'           => $this->resource->braking_torque,
            'winding_type'             => $this->resource->winding_type,
            'source_info'              => $this->resource->source_info,
            'input_voltage'            => $this->resource->input_voltage,
            'mechanical_hp'            => $this->resource->mechanical_hp,
            'hub_to_hub'               => $this->resource->hub_to_hub,
            'nominal_capacity'         => $this->resource->nominal_capacity,
            'wheel_dimensions'         => $this->resource->wheel_dimensions,
        ];
    }

    public static function jsonSchema(): array
    {
        return [
            'type'                 => ['object'],
            'properties'           => [
                'motor_type'               => ['type' => ['string', 'null']],
                'duty_rating'              => ['type' => ['string', 'null']],
                'voltage'                  => ['type' => ['string', 'null']],
                'ph'                       => ['type' => ['integer', 'null']],
                'hz'                       => ['type' => ['integer', 'null']],
                'run_capacitor_size'       => ['type' => ['string', 'null']],
                'start_capacitor_size'     => ['type' => ['string', 'null']],
                'rpm'                      => ['type' => ['string', 'null']],
                'output_hp'                => ['type' => ['string', 'null']],
                'frame_type'               => ['type' => ['string', 'null']],
                'rotation'                 => ['type' => ['string', 'null']],
                'speed'                    => ['type' => ['string', 'null']],
                'shaft_diameter'           => ['type' => ['string', 'null']],
                'shaft_keyway'             => ['type' => ['string', 'null']],
                'bearing_type'             => ['type' => ['string', 'null']],
                'fla'                      => ['type' => ['string', 'null']],
                'mounting_type'            => ['type' => ['string', 'null']],
                'shaft_length'             => ['type' => ['string', 'null']],
                'replaceable_bearings'     => ['type' => ['string', 'null']],
                'motor_diameter'           => ['type' => ['string', 'null']],
                'motor_height'             => ['type' => ['string', 'null']],
                'enclosure_type'           => ['type' => ['string', 'null']],
                'material_type'            => ['type' => ['string', 'null']],
                'weight'                   => ['type' => ['string', 'null']],
                'protection'               => ['type' => ['string', 'null']],
                'rla'                      => ['type' => ['string', 'null']],
                'lra'                      => ['type' => ['string', 'null']],
                'service_factor'           => ['type' => ['string', 'null']],
                'power_factor'             => ['type' => ['string', 'null']],
                'cfm'                      => ['type' => ['string', 'null']],
                'efficiency'               => ['type' => ['string', 'null']],
                'alternate_part_numbers'   => ['type' => ['string', 'null']],
                'output_watts'             => ['type' => ['string', 'null']],
                'input_watts'              => ['type' => ['string', 'null']],
                'ring_size'                => ['type' => ['string', 'null']],
                'resilient_ring_dimension' => ['type' => ['string', 'null']],
                'armature_amps'            => ['type' => ['string', 'null']],
                'field_amps'               => ['type' => ['string', 'null']],
                'service_factor_amps'      => ['type' => ['string', 'null']],
                'multi_voltage'            => ['type' => ['string', 'null']],
                'rotation_orientation'     => ['type' => ['string', 'null']],
                'mounting_angle'           => ['type' => ['string', 'null']],
                'shaft_type'               => ['type' => ['string', 'null']],
                'conduit_box_orientation'  => ['type' => ['string', 'null']],
                'torque_type'              => ['type' => ['string', 'null']],
                'drive_type'               => ['type' => ['string', 'null']],
                'misc'                     => ['type' => ['string', 'null']],
                'armature_voltage'         => ['type' => ['string', 'null']],
                'field_voltage'            => ['type' => ['string', 'null']],
                'start_type'               => ['type' => ['string', 'null']],
                'output_voltage'           => ['type' => ['string', 'null']],
                'trademark_name'           => ['type' => ['string', 'null']],
                'module_part_number'       => ['type' => ['string', 'null']],
                'included_with'            => ['type' => ['string', 'null']],
                'operating_temperature'    => ['type' => ['string', 'null']],
                'electrical_notes'         => ['type' => ['string', 'null']],
                'constant_torque_speed'    => ['type' => ['string', 'null']],
                'variable_torque_speed'    => ['type' => ['string', 'null']],
                'start_torque'             => ['type' => ['string', 'null']],
                'run_torque'               => ['type' => ['string', 'null']],
                'full_load_torque'         => ['type' => ['string', 'null']],
                'load_factor'              => ['type' => ['string', 'null']],
                'frame_diameter'           => ['type' => ['string', 'null']],
                'cooling_type'             => ['type' => ['string', 'null']],
                'notes'                    => ['type' => ['string', 'null']],
                'a_dimension'              => ['type' => ['string', 'null']],
                'b_dimension'              => ['type' => ['string', 'null']],
                'total_length'             => ['type' => ['string', 'null']],
                'efficiency_type'          => ['type' => ['string', 'null']],
                'shaft_dimensions'         => ['type' => ['string', 'null']],
                'fan_blade_dimensions'     => ['type' => ['string', 'null']],
                'stack'                    => ['type' => ['string', 'null']],
                'part_type'                => ['type' => ['string', 'null']],
                'lead_length'              => ['type' => ['string', 'null']],
                'capacitor_part_number'    => ['type' => ['string', 'null']],
                'eisa_rating'              => ['type' => ['string', 'null']],
                'bissc_rating'             => ['type' => ['string', 'null']],
                'shaft_orientation'        => ['type' => ['string', 'null']],
                'run_type'                 => ['type' => ['string', 'null']],
                'number_of_poles'          => ['type' => ['string', 'null']],
                'correct_part_number'      => ['type' => ['string', 'null']],
                'mount_part_number'        => ['type' => ['string', 'null']],
                'iec_rating'               => ['type' => ['string', 'null']],
                'braking_torque'           => ['type' => ['string', 'null']],
                'winding_type'             => ['type' => ['string', 'null']],
                'source_info'              => ['type' => ['string', 'null']],
                'input_voltage'            => ['type' => ['string', 'null']],
                'mechanical_hp'            => ['type' => ['string', 'null']],
                'hub_to_hub'               => ['type' => ['string', 'null']],
                'nominal_capacity'         => ['type' => ['string', 'null']],
                'wheel_dimensions'         => ['type' => ['string', 'null']],
            ],
            'required'             => [
                'motor_type',
                'duty_rating',
                'voltage',
                'ph',
                'hz',
                'run_capacitor_size',
                'rpm',
                'output_hp',
                'frame_type',
                'rotation',
                'speed',
                'shaft_diameter',
                'shaft_keyway',
                'bearing_type',
                'fla',
                'mounting_type',
                'shaft_length',
                'replaceable_bearings',
                'motor_diameter',
                'motor_height',
                'enclosure_type',
                'material_type',
                'weight',
                'protection',
                'rla',
                'lra',
                'service_factor',
                'power_factor',
                'cfm',
                'start_capacitor_size',
                'efficiency',
                'alternate_part_numbers',
                'output_watts',
                'input_watts',
                'ring_size',
                'resilient_ring_dimension',
                'armature_amps',
                'field_amps',
                'service_factor_amps',
                'multi_voltage',
                'rotation_orientation',
                'mounting_angle',
                'shaft_type',
                'conduit_box_orientation',
                'torque_type',
                'drive_type',
                'misc',
                'armature_voltage',
                'field_voltage',
                'start_type',
                'output_voltage',
                'trademark_name',
                'module_part_number',
                'included_with',
                'operating_temperature',
                'electrical_notes',
                'constant_torque_speed',
                'variable_torque_speed',
                'start_torque',
                'run_torque',
                'full_load_torque',
                'load_factor',
                'frame_diameter',
                'cooling_type',
                'notes',
                'a_dimension',
                'b_dimension',
                'total_length',
                'efficiency_type',
                'shaft_dimensions',
                'fan_blade_dimensions',
                'stack',
                'part_type',
                'lead_length',
                'capacitor_part_number',
                'eisa_rating',
                'bissc_rating',
                'shaft_orientation',
                'run_type',
                'number_of_poles',
                'correct_part_number',
                'mount_part_number',
                'iec_rating',
                'braking_torque',
                'winding_type',
                'source_info',
                'input_voltage',
                'mechanical_hp',
                'hub_to_hub',
                'nominal_capacity',
                'wheel_dimensions',
            ],
            'additionalProperties' => false,
        ];
    }
}
