---
    name: Build and Push Python Image to Google Cloud Platform
    on:
      push:
        branches: [ main ]
    jobs:
      build-push-gcr:
        name: Build and Push to GCP
        runs-on: ubuntu-latest
        env:
          IMAGE_NAME: laravel-test
          PROJECT_ID: bluon-platform-dev
        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: 'Authenticate to Google Cloud'
          uses: 'google-github-actions/auth@v0.6.0'
          with:
            credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'
            token_format: 'access_token'

        - name: Docker login
          run: gcloud auth print-access-token | docker login -u oauth2accesstoken  --password-stdin https://us-west2-docker.pkg.dev
                  
        - name: Build Docker Image
          run: |-                                  
            docker build -t $IMAGE_NAME:latest . 
            docker-compose up

            
        - name: Push Docker Image to Artifact Registry   
          run: |-
            docker tag $IMAGE_NAME:latest us-west2-docker.pkg.dev/$PROJECT_ID/docker/$IMAGE_NAME:latest
            docker push us-west2-docker.pkg.dev/$PROJECT_ID/docker/$IMAGE_NAME:latest   
