---
    name: Build and Push Python Image to Google Cloud Platform
    on:
      push:
        branches: [ main ]
    jobs:
      build-push-gcr:
        name: Build and Push to GCP
        runs-on: ubuntu-latest
        env:
          IMAGE_NAME: laravel-test
          PROJECT_ID: david-experiment
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        
        - name: Setup PHP
          uses: shivammathur/setup-php@master
          with:
            php-version: 8.2
            extensions: mbstring, bcmath, grpc

        - name: Install Composer Dependencies
          run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

        - uses: google-github-actions/setup-gcloud@main
          with:
            service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
            project_id: ${{ env.PROJECT_ID }}
            export_default_credentials: true

        - name: Build Docker Image
          run: |-                      
            docker build -t $IMAGE_NAME:latest .
    
        - name: Automatic Tagging of Releases
          id: increment-git-tag
          run: |
            bash ./scripts/git_update.sh -v major
    
        - name: Configure Docker Client
          run: |-
            gcloud auth login
            gcloud auth configure-docker --quiet
            gcloud auth configure-docker us-west2-docker.pkg.dev --quiet
    
        - name: Push Docker Image to Container Registry (GCR)
          env:
            GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
          run: |-
            docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
            docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
            docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
            docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
    
        - name: Push Docker Image to Artifact Registry
          env:
            GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
          run: |-
            docker tag $IMAGE_NAME:latest us-west2-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
            docker tag $IMAGE_NAME:latest us-west2-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
            docker push us-west2-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
            docker push us-west2-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG    
