<?php

namespace App\Http\Resources\Models;

use App\Http\Resources\HasJsonSchema;
use App\Models\MeteringDevice;
use Illuminate\Http\Resources\Json\JsonResource;

/**
 * @property MeteringDevice $resource
 */
class MeteringDeviceResource extends JsonResource implements HasJsonSchema
{
    public function __construct(MeteringDevice $resource)
    {
        parent::__construct($resource);
    }

    public function toArray($request)
    {
        return [
            'rated_refrigerant'              => $this->resource->rated_refrigerant,
            'nominal_capacity'               => $this->resource->nominal_capacity,
            'inlet_diameter'                 => $this->resource->inlet_diameter,
            'inlet_connection_type'          => $this->resource->inlet_connection_type,
            'outlet_diameter'                => $this->resource->outlet_diameter,
            'outlet_connection_type'         => $this->resource->outlet_connection_type,
            'equalizer'                      => $this->resource->equalizer,
            'external_equalizer_connection'  => $this->resource->external_equalizer_connection,
            'bidirectional'                  => $this->resource->bidirectional,
            'adjustable'                     => $this->resource->adjustable,
            'configuration'                  => $this->resource->configuration,
            'supply_voltage'                 => $this->resource->supply_voltage,
            'motor_type'                     => $this->resource->motor_type,
            'control_steps'                  => $this->resource->control_steps,
            'step_rate'                      => $this->resource->step_rate,
            'orfice_size'                    => $this->resource->orfice_size,
            'capillary_tube_length'          => $this->resource->capillary_tube_length,
            'number_of_headers'              => $this->resource->number_of_headers,
            'spring_type'                    => $this->resource->spring_type,
            'check_valve'                    => $this->resource->check_valve,
            'hermetic'                       => $this->resource->hermetic,
            'balanced_port'                  => $this->resource->balanced_port,
            'applications'                   => $this->resource->applications,
            'element_size'                   => $this->resource->element_size,
            'body_type'                      => $this->resource->body_type,
            'thermostatic_charge'            => $this->resource->thermostatic_charge,
            'mesh_strainer'                  => $this->resource->mesh_strainer,
            'max_operating_pressures'        => $this->resource->max_operating_pressures,
            'max_differential_pressure_drop' => $this->resource->max_differential_pressure_drop,
            'ambient_temperature'            => $this->resource->ambient_temperature,
            'refrigerant_temperature'        => $this->resource->refrigerant_temperature,
            'current'                        => $this->resource->current,
            'drive_frequency'                => $this->resource->drive_frequency,
            'phase_resistance'               => $this->resource->phase_resistance,
            'compatible_oils'                => $this->resource->compatible_oils,
            'cable_type'                     => $this->resource->cable_type,
            'max_power_input'                => $this->resource->max_power_input,
            'step_angle'                     => $this->resource->step_angle,
            'resolution'                     => $this->resource->resolution,
            'connections'                    => $this->resource->connections,
            'closing_steps'                  => $this->resource->closing_steps,
            'minimum_steps'                  => $this->resource->minimum_steps,
            'hold_current'                   => $this->resource->hold_current,
            'percent_duty'                   => $this->resource->percent_duty,
            'stroke'                         => $this->resource->stroke,
            'max_internal_leakage'           => $this->resource->max_internal_leakage,
            'max_external_leakage'           => $this->resource->max_external_leakage,
        ];
    }

    public static function jsonSchema(): array
    {
        return [
            'type'                 => ['object'],
            'properties'           => [
                'rated_refrigerant'              => ['type' => ['string', 'null']],
                'nominal_capacity'               => ['type' => ['string', 'null']],
                'inlet_diameter'                 => ['type' => ['string', 'null']],
                'inlet_connection_type'          => ['type' => ['string', 'null']],
                'outlet_diameter'                => ['type' => ['string', 'null']],
                'outlet_connection_type'         => ['type' => ['string', 'null']],
                'equalizer'                      => ['type' => ['string', 'null']],
                'external_equalizer_connection'  => ['type' => ['string', 'null']],
                'bidirectional'                  => ['type' => ['boolean', 'null']],
                'adjustable'                     => ['type' => ['boolean', 'null']],
                'configuration'                  => ['type' => ['string', 'null']],
                'supply_voltage'                 => ['type' => ['string', 'null']],
                'motor_type'                     => ['type' => ['string', 'null']],
                'control_steps'                  => ['type' => ['integer', 'null']],
                'step_rate'                      => ['type' => ['string', 'null']],
                'orfice_size'                    => ['type' => ['number', 'null']],
                'capillary_tube_length'          => ['type' => ['string', 'null']],
                'number_of_headers'              => ['type' => ['integer', 'null']],
                'spring_type'                    => ['type' => ['string', 'null']],
                'check_valve'                    => ['type' => ['string', 'null']],
                'hermetic'                       => ['type' => ['boolean', 'null']],
                'balanced_port'                  => ['type' => ['boolean', 'null']],
                'applications'                   => ['type' => ['string', 'null']],
                'element_size'                   => ['type' => ['string', 'null']],
                'body_type'                      => ['type' => ['string', 'null']],
                'thermostatic_charge'            => ['type' => ['string', 'null']],
                'mesh_strainer'                  => ['type' => ['boolean', 'null']],
                'max_operating_pressures'        => ['type' => ['string', 'null']],
                'max_differential_pressure_drop' => ['type' => ['string', 'null']],
                'ambient_temperature'            => ['type' => ['string', 'null']],
                'refrigerant_temperature'        => ['type' => ['string', 'null']],
                'current'                        => ['type' => ['string', 'null']],
                'drive_frequency'                => ['type' => ['string', 'null']],
                'phase_resistance'               => ['type' => ['string', 'null']],
                'compatible_oils'                => ['type' => ['string', 'null']],
                'cable_type'                     => ['type' => ['string', 'null']],
                'max_power_input'                => ['type' => ['string', 'null']],
                'step_angle'                     => ['type' => ['string', 'null']],
                'resolution'                     => ['type' => ['string', 'null']],
                'connections'                    => ['type' => ['string', 'null']],
                'closing_steps'                  => ['type' => ['string', 'null']],
                'minimum_steps'                  => ['type' => ['integer', 'null']],
                'hold_current'                   => ['type' => ['string', 'null']],
                'percent_duty'                   => ['type' => ['string', 'null']],
                'stroke'                         => ['type' => ['string', 'null']],
                'max_internal_leakage'           => ['type' => ['string', 'null']],
                'max_external_leakage'           => ['type' => ['string', 'null']],
            ],
            'required'             => [
                'rated_refrigerant',
                'nominal_capacity',
                'inlet_diameter',
                'inlet_connection_type',
                'outlet_diameter',
                'outlet_connection_type',
                'equalizer',
                'external_equalizer_connection',
                'bidirectional',
                'adjustable',
                'configuration',
                'supply_voltage',
                'motor_type',
                'control_steps',
                'step_rate',
                'orfice_size',
                'capillary_tube_length',
                'number_of_headers',
                'spring_type',
                'check_valve',
                'hermetic',
                'balanced_port',
                'applications',
                'element_size',
                'body_type',
                'thermostatic_charge',
                'mesh_strainer',
                'max_operating_pressures',
                'max_differential_pressure_drop',
                'ambient_temperature',
                'refrigerant_temperature',
                'current',
                'drive_frequency',
                'phase_resistance',
                'compatible_oils',
                'cable_type',
                'max_power_input',
                'step_angle',
                'resolution',
                'connections',
                'closing_steps',
                'minimum_steps',
                'hold_current',
                'percent_duty',
                'stroke',
                'max_internal_leakage',
                'max_external_leakage',
            ],
            'additionalProperties' => false,
        ];
    }
}
